version: "3.4"

DISPLAY=192.168.0.104:0.0

services:
  arduino:
    image: darduino
    container_name: arduino
    network_mode: "host"
    environment:
      - "DISPLAY=${DISPLAY}"
    volumes:
      # - "/tmp/.X11-unix:/tmp/.X11-unix"
      # - "/dev/ttyUSB0:/dev/ttyUSB0"
      -v .:/home/developer/Arduino
    command: "arduino"
    privileged: true